"""Shell completion support for envault CLI."""
from __future__ import annotations

import os
from typing import List

SUPPORTED_SHELLS = ("bash", "zsh", "fish")

BANNER = "# Generated by envault — do not edit manually"


class CompletionError(Exception):
    pass


def generate_bash(commands: List[str]) -> str:
    cmds = " ".join(commands)
    return f"""{BANNER}
_envault_completions() {{
    local cur prev words cword
    _init_completion || return
    if [[ $cword -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "{cmds}" -- "$cur") )
    fi
}}
complete -F _envault_completions envault
"""


def generate_zsh(commands: List[str]) -> str:
    cmds = "\n".join(f"    '{c}'" for c in commands)
    return f"""{BANNER}
#compdef envault
_envault() {{
    local -a cmds
    cmds=(
{cmds}
    )
    _describe 'command' cmds
}}
_envault
"""


def generate_fish(commands: List[str]) -> str:
    lines = [BANNER]
    for cmd in commands:
        lines.append(f"complete -c envault -f -n '__fish_use_subcommand' -a '{cmd}'")
    return "\n".join(lines) + "\n"


def generate_completion(shell: str, commands: List[str]) -> str:
    """Return completion script for the given shell."""
    shell = shell.lower()
    if shell not in SUPPORTED_SHELLS:
        raise CompletionError(
            f"Unsupported shell '{shell}'. Choose from: {', '.join(SUPPORTED_SHELLS)}"
        )
    generators = {
        "bash": generate_bash,
        "zsh": generate_zsh,
        "fish": generate_fish,
    }
    return generators[shell](commands)


def write_completion_file(shell: str, commands: List[str], path: str) -> str:
    """Write completion script to *path* and return the path."""
    script = generate_completion(shell, commands)
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(script)
    return path
